import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";

// Menambahkan Font Family Dari Google Font
import { Amiri_Quran } from "next/font/google";

export const amiri = Amiri_Quran({
  weight: ['400'],
  subsets: ["arabic"],
  variable: '--font-amiri'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-[#020617] via-[#0f172a] to-[#064e3b] animate-gradient
`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
